language: go

go:
  - 1.10.2
    
# tarvis生命周期执行顺序详见官网文档
before_install:
- git config --global user.name "fydy"
- git config --global user.email "hargrovd@mail.lcc.edu"
- rm -rf *
- git clone -b gh-pages https://github.com/fydy/hugo.git

install:
- cd hugo

after_success:
- git init
- git remote add origin https://gitlab.com/fydy/fydy.gitlab.io.git
- git add .
- git commit -m "Initial commit"
# 这里的 REPO_TOKEN 即之前在 travis 项目的环境变量里添加的

# Gitlab Pages
- git push --force --quiet "https://fydy:${GI_TOKEN}@${GI_REF}" master

env:
 global:
   # Gitlab Pages
   - GI_REF: gitlab.com/fydy/fydy.gitlab.io.git
