language: node_js

sudo: required
addons:
 chrome: stable

cache:
  apt: true
  directories:
    - node_modules

node_js:
  - "stable"


# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - rm -rf *
  - npm install Mirror -g

install:
  - mirror init
  - mirror build

after_success:
  - git init
  - git config user.name "fydy"
  - git config user.email "edu@yuns.me"
  - git add .
  - git commit -m "update"
  - git checkout -b blog
  - git push --quiet --force https://$hugo@github.com/fydy/hugo.git blog
