language: go

go:
  - 1.12.6

env:
 global:
   - GH_REF: github.com/fydy/hugo.git


sudo: required

git:
  submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - rm -rf themes/even && git clone https://github.com/olOwOlo/hugo-theme-even themes/even && rm -rf themes/even/.git
  - sed -i '/^base/'d config.toml
  - sed -i '/^title = "/a\baseurl = "https://lvshi.cf/hugo/"' config.toml
  - sed -i "s/olOwOlo/fydy/g" themes/even/layouts/partials/footer.html
  - sed -i "s/hugo-theme-even/hugo/g" themes/even/layouts/partials/footer.html
  - sed -i "s/Even/行者无境/g" themes/even/layouts/partials/footer.html
  - sed -i "58s/Even/行者无境/g" config.toml
  - sed -i "4s/Even - A super concise theme for Hugo/分享感悟！！！/g" config.toml
  - sed -i "23s/olOwOlo/行者无境/g" config.toml
#  - sed -i '30,34d' config.toml
#  - sudo apt-get install axel
#  - curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
#  - sudo apt-get install git-lfs
#  - git lfs install
  - cd ./themes/even/
  - git init && git remote add origin https://github.com/fydy/hugo.git && git pull origin master:gh-pages && rm -rf .git
  - cd .. && cd ..
  - sed -i "s/fonts.gstatic.com/fonts-gstatic.proxy.ustclug.org/g" `grep fonts.gstatic.com -rnl ./`
  - sed -i "s/fonts.googleapis.com/fonts.proxy.ustclug.org/g" `grep fonts.googleapis.com -rnl ./`
  - sed -i "s/ajax.googleapis.com/ajax.proxy.ustclug.org/g" `grep ajax.googleapis.com -rnl ./`
  - sed -i "s/maps.googleapis.com/ditu.google.cn/g" `grep maps.googleapis.com -rnl ./`


install:
  - export HUGO_VERSION=0.55.6
  - sudo pip install Pygments
  - wget https://github.com/spf13/hugo/releases/download/v$HUGO_VERSION/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar xzf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - chmod a+x hugo

script:
  - ./hugo

after_script:
  - cd ./public
  - git init
  - git config user.name "fydy"
  - git config user.email "edu@yuns.me"
  - git add .
  - git commit -m "Update"
  - git checkout -b master
  - git push --quiet --force https://$hugo@github.com/fydy/hugo.git master
