language: go

go:
  - 1.11

branches:
  only:
    - source

env:
 global:
   - GH_REF: github.com/fydy/hugo.git


sudo: required

git:
  submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i '/^base/'d config.toml
  - sed -i '/^title = "/a\baseurl = "https://lvshi.cf/hugo/"' config.toml
  - sed -i "s/olOwOlo/fydy/g" themes/even/layouts/partials/footer.html
  - sed -i "s/hugo-theme-even/hugo/g" themes/even/layouts/partials/footer.html
  - sed -i "s/Even/行一法苑/g" themes/even/layouts/partials/footer.html

install:
  - export HUGO_VERSION=0.51
  - sudo pip install Pygments
  - wget https://github.com/spf13/hugo/releases/download/v$HUGO_VERSION/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar xzf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - chmod a+x hugo

script:
  - ./hugo

after_script:
  - cd ./public
  - git init
  - git config user.name "fydy"
  - git config user.email "edu@yuns.me"
  - git add .
  - git commit -m "Update"
  - git checkout -b master
  - git push --quiet --force https://$hugo@github.com/fydy/hugo.git master
